services:
  db:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: evently
      POSTGRES_PASSWORD: evently-pass
      POSTGRES_DB: evently
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
