// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: events.sql

package models

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createEvent = `-- name: CreateEvent :one
insert into events (title, description, organizer_id, category_id, location, status, starting_time, ending_time)
values ($1, $2, $3, $4, $5, $6, $7, $8)
returning id, title, description, status, category_id, organizer_id, location, starting_time, ending_time, created_at, updated_at
`

type CreateEventParams struct {
	Title        string      `json:"title"`
	Description  string      `json:"description"`
	OrganizerID  uuid.UUID   `json:"organizer_id"`
	CategoryID   int32       `json:"category_id"`
	Location     pgtype.Text `json:"location"`
	Status       string      `json:"status"`
	StartingTime time.Time   `json:"starting_time"`
	EndingTime   time.Time   `json:"ending_time"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.Title,
		arg.Description,
		arg.OrganizerID,
		arg.CategoryID,
		arg.Location,
		arg.Status,
		arg.StartingTime,
		arg.EndingTime,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CategoryID,
		&i.OrganizerID,
		&i.Location,
		&i.StartingTime,
		&i.EndingTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEventById = `-- name: DeleteEventById :one
delete from events
where id = $1
returning id, title, description, status, category_id, organizer_id, location, starting_time, ending_time, created_at, updated_at
`

func (q *Queries) DeleteEventById(ctx context.Context, id uuid.UUID) (Event, error) {
	row := q.db.QueryRow(ctx, deleteEventById, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CategoryID,
		&i.OrganizerID,
		&i.Location,
		&i.StartingTime,
		&i.EndingTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEventById = `-- name: GetEventById :one
select id, title, description, status, category_id, organizer_id, location, starting_time, ending_time, created_at, updated_at from events
where id = $1
`

func (q *Queries) GetEventById(ctx context.Context, id uuid.UUID) (Event, error) {
	row := q.db.QueryRow(ctx, getEventById, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CategoryID,
		&i.OrganizerID,
		&i.Location,
		&i.StartingTime,
		&i.EndingTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLatestEvents = `-- name: ListLatestEvents :many
select id, title, description, status, category_id, organizer_id, location, starting_time, ending_time, created_at, updated_at from events
order by created_at desc
limit $1
offset $2
`

type ListLatestEventsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListLatestEvents(ctx context.Context, arg ListLatestEventsParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listLatestEvents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.CategoryID,
			&i.OrganizerID,
			&i.Location,
			&i.StartingTime,
			&i.EndingTime,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEvent = `-- name: UpdateEvent :one
update events
set title = $2, description = $3, status = $4, category_id = $5, starting_time = $6, updated_at = now()
where id = $1
returning id, title, description, status, category_id, organizer_id, location, starting_time, ending_time, created_at, updated_at
`

type UpdateEventParams struct {
	ID           uuid.UUID `json:"id"`
	Title        string    `json:"title"`
	Description  string    `json:"description"`
	Status       string    `json:"status"`
	CategoryID   int32     `json:"category_id"`
	StartingTime time.Time `json:"starting_time"`
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, updateEvent,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.CategoryID,
		arg.StartingTime,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CategoryID,
		&i.OrganizerID,
		&i.Location,
		&i.StartingTime,
		&i.EndingTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
