// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package models

import (
	"context"

	uuid "github.com/google/uuid"
)

type Querier interface {
	CreateCategory(ctx context.Context, name string) (Category, error)
	CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error)
	CreateUser(ctx context.Context, auth0ID string) (User, error)
	DeleteById(ctx context.Context, id int32) (Category, error)
	DeleteByName(ctx context.Context, lower string) (Category, error)
	DeleteEventById(ctx context.Context, id uuid.UUID) (Event, error)
	DeleteUserById(ctx context.Context, id uuid.UUID) (User, error)
	GetEventById(ctx context.Context, id uuid.UUID) (Event, error)
	GetUserByAuth0ID(ctx context.Context, auth0ID string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	ListCategories(ctx context.Context) ([]Category, error)
	ListLatestEvents(ctx context.Context, arg ListLatestEventsParams) ([]Event, error)
	UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error)
	categoryExistsById(ctx context.Context, id int32) (bool, error)
}

var _ Querier = (*Queries)(nil)
