// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user.sql

package models

import (
	"context"

	uuid "github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
insert into users(auth0_id)
values($1)
returning id, auth0_id, created_at
`

func (q *Queries) CreateUser(ctx context.Context, auth0ID string) (User, error) {
	row := q.db.QueryRow(ctx, createUser, auth0ID)
	var i User
	err := row.Scan(&i.ID, &i.Auth0ID, &i.CreatedAt)
	return i, err
}

const deleteUserById = `-- name: DeleteUserById :one
delete from users 
where id = $1
returning id, auth0_id, created_at
`

func (q *Queries) DeleteUserById(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, deleteUserById, id)
	var i User
	err := row.Scan(&i.ID, &i.Auth0ID, &i.CreatedAt)
	return i, err
}

const getUserByAuth0ID = `-- name: GetUserByAuth0ID :one
select id, auth0_id, created_at from users where auth0_id = $1
`

func (q *Queries) GetUserByAuth0ID(ctx context.Context, auth0ID string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByAuth0ID, auth0ID)
	var i User
	err := row.Scan(&i.ID, &i.Auth0ID, &i.CreatedAt)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
select id, auth0_id, created_at from users where id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(&i.ID, &i.Auth0ID, &i.CreatedAt)
	return i, err
}
