// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: categories.sql

package datab

import (
	"context"
)

const createCategory = `-- name: CreateCategory :one
insert into categories (name) values($1) returning id, name, created_at
`

func (q *Queries) CreateCategory(ctx context.Context, name string) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory, name)
	var i Category
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const deleteById = `-- name: DeleteById :one
delete from categories where id = $1 returning id, name, created_at
`

func (q *Queries) DeleteById(ctx context.Context, id int32) (Category, error) {
	row := q.db.QueryRow(ctx, deleteById, id)
	var i Category
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const deleteByName = `-- name: DeleteByName :one
delete from categories where lower(name) = lower($1) returning id, name, created_at
`

func (q *Queries) DeleteByName(ctx context.Context, lower string) (Category, error) {
	row := q.db.QueryRow(ctx, deleteByName, lower)
	var i Category
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const listCategories = `-- name: ListCategories :many
select id, name, created_at from categories
`

func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
