// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package datab

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID        int32              `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Event struct {
	ID           pgtype.UUID        `json:"id"`
	Title        string             `json:"title"`
	Description  string             `json:"description"`
	Status       string             `json:"status"`
	CategoryID   int32              `json:"category_id"`
	StartingTime pgtype.Timestamptz `json:"starting_time"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
