// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package datab

import (
	"context"
)

type Querier interface {
	CreateCategory(ctx context.Context, name string) (Category, error)
	DeleteById(ctx context.Context, id int32) (Category, error)
	DeleteByName(ctx context.Context, lower string) (Category, error)
	ListCategories(ctx context.Context) ([]Category, error)
}

var _ Querier = (*Queries)(nil)
